[defaults]
checkout_dir = "~/Projects/references"

[[sources]]
name = "baoyu-skills"

[sources.remote]
url = "https://github.com/JimLiu/baoyu-skills.git"

[[sources]]
name = "frontend-slides"

[sources.remote]
url = "https://github.com/zarazhangrui/frontend-slides.git"

[[sources]]
name = "guizang-ppt-skill"

[sources.remote]
url = "https://github.com/op7418/guizang-ppt-skill.git"
